export const userColumns = [
    { field: "id", headerName: "Transaction ID", width: 120 },
    {field: "product", headerName: "Product", width: 150 },
    {
      field: "first",
      headerName: "First Name",
      width: 100,
    },
    {
        field: "last",
        headerName: "Last Name",
        width: 100,
      },
    { field: "address", headerName: "Address", width: 300 },
    { field: "date", headerName: "Date", width: 120 },
    { field: "amount", headerName: "Amount", width: 70 },
    { field: "status", headerName: "Status", width: 100 },
  ];
  
  export const userRows = [
    {
        id: 738333399,
        product: "Citrus Burst",
        first: "Grant",
        last: "Smoth",
        address:"123 Uma Lane, Umatropolis, USA",
        date: "11-27-2023",
        amount: 1,
        status: "Approved",
      },
      {
        id: 777253119,
        product: "Lavender Dreams",
        first: "Ashton",
        last: "Hanes",
        address:"537 Mayfair Ave. Bridgeton, NJ 08302",
        date: "02-05-2023",
        amount: 3,
        status: "Pending",
      },
      {
        id: 116351733,
        product: "Mountain Pines",
        first: "John",
        last: "Smith",
        address:"123 Uma Street, Umatropolis, UR 33800",
        date: "01-06-2023",
        amount: 2,
        status: "Approved",
      },
      {
        id: 677215481,
        product: "Lavender Dreams",
        first: "Sheldon",
        last: "Williams",
        address:"313 Edgewater Rd. Eugene, OR 97402 ",
        date: "08-21-2022",
        amount: 1,
        status: "Pending",
      },
      
      {
        id: 238393399,
        product: "Ocean Breeze",
        first: "Bria",
        last: "Padberg",
        address:"6 George Dr. Pleasanton, CA 94566",
        date: "05-08-2022",
        amount: 2,
        status: "Approved",
      },
      {
        id: 611933399,
        product: "Vanilla Delight",
        first: "Bria",
        last: "Padberg",
        date: "02-14-2022",
        address:"6 George Dr. Pleasanton, CA 94566",
        amount: 1,
        status: "Approved",
      },
  ];